[build-system]
requires = [
    "setuptools>=64",
    "setuptools-scm[toml]>=6.2",
    "Cython",
    "py-cpuinfo"
]
build-backend = "setuptools.build_meta"

[project]
name = "numcodecs"
description = """
A Python package providing buffer compression and transformation codecs \
for use in data storage and communication applications."""
readme =  "README.rst"
dependencies = [
    "numpy>=1.7",
]
requires-python = ">=3.10"
dynamic = [
  "version",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
maintainers = [
    { name = "Alistair Miles", email = "alimanfoo@googlemail.com" },
]
license = { text = "MIT" }

[project.urls]
"Bug Tracker" = "https://github.com/zarr-developers/numcodecs/issues"
Changelog = "https://numcodecs.readthedocs.io/en/stable/release.html"
Documentation = "https://numcodecs.readthedocs.io/"
Homepage = "https://github.com/zarr-developers/numcodecs"

[project.optional-dependencies]
docs = [
    "sphinx<7.0.0",
    "sphinx-issues",
    "pydata-sphinx-theme",
    "numpydoc",
    "mock",
]
test = [
    "coverage",
    "pytest",
    "pytest-cov",
]
test_extras = [
    "importlib_metadata",
]
msgpack = [
    "msgpack",
]
zfpy = [
    "zfpy>=1.0.0",
]
pcodec = [
    "pcodec>=0.1.0",
]

[project.entry-points."zarr.codecs"]
"https://zarr.dev/numcodecs/blosc" = "numcodecs.zarr3:BloscCodec"
"https://zarr.dev/numcodecs/lz4" = "numcodecs.zarr3:Lz4Codec"
"https://zarr.dev/numcodecs/zstd" = "numcodecs.zarr3:ZstdCodec"
"https://zarr.dev/numcodecs/zlib" = "numcodecs.zarr3:ZlibCodec"
"https://zarr.dev/numcodecs/gzip" = "numcodecs.zarr3:GzipCodec"
"https://zarr.dev/numcodecs/bz2" = "numcodecs.zarr3:Bz2Codec"
"https://zarr.dev/numcodecs/lzma" = "numcodecs.zarr3:LzmaCodec"
"https://zarr.dev/numcodecs/shuffle" = "numcodecs.zarr3:ShuffleCodec"
"https://zarr.dev/numcodecs/delta" = "numcodecs.zarr3:DeltaCodec"
"https://zarr.dev/numcodecs/bitround" = "numcodecs.zarr3:BitroundCodec"
"https://zarr.dev/numcodecs/fixedscaleoffset" = "numcodecs.zarr3:FixedScaleOffsetCodec"
"https://zarr.dev/numcodecs/quantize" = "numcodecs.zarr3:QuantizeCodec"
"https://zarr.dev/numcodecs/packbits" = "numcodecs.zarr3:PackbitsCodec"
"https://zarr.dev/numcodecs/astype" = "numcodecs.zarr3:AsTypeCodec"
"https://zarr.dev/numcodecs/crc32" = "numcodecs.zarr3:Crc32Codec"
"https://zarr.dev/numcodecs/adler32" = "numcodecs.zarr3:Adler32Codec"
"https://zarr.dev/numcodecs/fletcher32" = "numcodecs.zarr3:Fletcher32Codec"
"https://zarr.dev/numcodecs/jenkins_lookup3" = "numcodecs.zarr3:JenkinsLookup3Codec"
"https://zarr.dev/numcodecs/pcodec" = "numcodecs.zarr3:PCodecCodec"
"https://zarr.dev/numcodecs/zfpy" = "numcodecs.zarr3:ZFPYCodec"

[tool.setuptools]
license-files = ["LICENSE.txt"]
package-dir = {"" = "."}
packages = ["numcodecs", "numcodecs.tests"]
zip-safe = false

[tool.setuptools.package-data]
numcodecs = [
    "tests/package_with_entrypoint/__init__.py",
    "tests/package_with_entrypoint-0.1.dist-info/entry_points.txt"
]

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "dirty-tag"
write_to = "numcodecs/version.py"

[tool.codespell]
skip = "./.git,fixture"
ignore-words-list = "ba, compiletime, hist, nd, unparseable"

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "pragma: ${PY_MAJOR_VERSION} no cover",
]

[tool.pytest.ini_options]
addopts = "--cov=numcodecs --cov-report xml --doctest-modules --doctest-glob=*.pyx"
doctest_optionflags = [
    "NORMALIZE_WHITESPACE",
    "ELLIPSIS",
    "IGNORE_EXCEPTION_DETAIL",
]
testpaths = [
    "numcodecs",
]
norecursedirs = [
    ".git",
    ".github",
    ".pytest_cache",
    "adhoc",
    "build",
    "c-blosc",
    "docs",
    "fixture",
    "notebooks",
    "numcodecs.egg-info",
]
[tool.cibuildwheel]
environment = { DISABLE_NUMCODECS_AVX2=1 }
[tool.cibuildwheel.macos]
environment = { MACOSX_DEPLOYMENT_TARGET=10.9, DISABLE_NUMCODECS_AVX2=1, CFLAGS="$CFLAGS -Wno-implicit-function-declaration" }
[[tool.cibuildwheel.overrides]]
select = "*-macosx_arm64"
environment = { DISABLE_NUMCODECS_AVX2=1, DISABLE_NUMCODECS_SSE2=1 }

[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "preserve"
